// Home.tsx
import React from 'react';
import { Provider } from 'react-redux';
import { ProductProvider } from '@/context/ProductContext';
import store from '@/store/store';
import Head from 'next/head';
import Header from '@/components/Header/Header';
import SearchResult from '@/components/SearchResult/SearchResult';
import styles from '@/styles/Home.module.css';

export default function Home() {

  return (
    <>
      <Head>
        <title>Mercado Libre Argentina - Donde comprar y vender de todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <ProductProvider>
          <Header />
          <main className={styles.main}>
            <SearchResult/>
          </main>
        </ProductProvider>
      </Provider>
    </>
  );
}
